# This is a basic workflow that is manually triggered

name: Manual workflow

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          gpg-private-key: ${{ secrets.GPG_SIGNING_KEY }} 
          gpg-passphrase: ${{ secrets.GPG_PASSPHRASE }}
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@e6e38bacfdf1a337459f332974bb2327a31aaf4b
#       - name: Import GPG Key
#         uses: crazy-max/ghaction-import-gpg@v5
#         with: 
#           gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }} 
#           passphrase: ${{ secrets.GPG_PASSPHRASE }}
#       - name: extract key
#         run: gpg --export-secret-keys -o /home/runner/secring.gpg
#         env:
#           PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
      - name: Publish package
        uses: gradle/gradle-build-action@67421db6bd0bf253fb4bd25b31ebb98943c375e1
        with:
          arguments: publishMavenJavaPublicationToMavenRepository
        env:
          MAVEN_USERNAME: ${{ secrets.sonatype_username }}
          MAVEN_PASSWORD: ${{ secrets.sonatype_password }}
          # signing.keyId: ${{ secrets.SIGNING_KEY_ID }}
          signing.password: ${{ secrets.SIGNING_KEY_PASSWORD }}
          # signing.secretKeyRingFile: ${{ secrets.SIGNING_SECRET_KEY_RING_FILE }}
          
